### ISSUE TITLE
Sending large Attachments created from MemoryStream fail with System.AggregateException

### ISSUE THREAD

**Issue by ekincaglar** [sendgrid/sendgrid-csharp#1016]
### Issue Summary
When we try to send a large attachment we get a System.AggregateException. The same code with smaller files, e.g. <20MB, work OK.

### Steps to Reproduce
1. Create an Attachment from a MemoryStream (see the code below)
2. Try to send the Attachment

### Code Snippet
```csharp
byte[] compressedBytes;
                using (var outStream = new MemoryStream())
                {
                    using (var archive = new ZipArchive(outStream, ZipArchiveMode.Create, true))
                    {
                        var fileInArchive = archive.CreateEntry("items.xlsx", System.IO.Compression.CompressionLevel.Optimal);
                        using (var entryStream = fileInArchive.Open())
                        {
                            using (var memoryStream = CustomHelperClass.GetExcelFile())
                            {
                                memoryStream.Position = 0;
                                memoryStream.CopyTo(entryStream);
                            }
                        }
                    }
                    compressedBytes = outStream.ToArray();
                }
MemoryStream attachmentStream = new MemoryStream(compressedBytes);
                    Attachment attachment = new Attachment(attachmentStream, "items.zip", System.Net.Mime.MediaTypeNames.Application.Zip);
```

### Exception/Log
```
System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SendGrid.Response.d__13.MoveNext() in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\Response.cs:line 106
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Ekin.Email.Sendgrid.SetLogsFromResponse(Response response)
   at Ekin.Email.Sendgrid.d__9.MoveNext()
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SendGrid.Response.d__13.MoveNext() in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\Response.cs:line 106<---
```

### Technical details:
* sendgrid-csharp version: 9.12.0
* VS Version: 16.6.1
* .Net Framework Version: 4.8.03752

**Comment by thinkingserious** [comment]
Hello @ekincaglar,

The total size of your message [should not exceed 30MB](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations). My guess is that you have run into that limit. [Here](https://sendgrid.com/docs/ui/sending-email/attachments-with-digioh/#limitations) is one workaround.

With best regards,

Elmer
