### ISSUE TITLE
Cannot add new dataset in VS 2017 Microsoft rdlc report designer

### ISSUE THREAD

**Issue by hrplinktest** [sendgrid/sendgrid-csharp#1083]
I was using SendGrid SMTP before but I changed it to API keys as followed by your recent requirement.  But then I just found out after spending my whole day of investigation that this caused an issue on our development environment.  We are using "Visual Studio 2017 Community Edition" and "Microsoft rdlc report designer for visual studio 14.2" and now the report designer is not working properly anymore (Eg. cannot add a new dataset or modify an existing dataset inside the rdlc file).  We got the latest stable version of SendGrid (9.22.0).  When I remove the reference to SendGrid dll file, the report designer is working properly.  But of course if I remove the reference to SendGrid, then the email system will not work anymore.

**Comment by thinkingserious** [comment]
Hello @hrplinktest,

Are there any error logs you can share with us? I don't have the "Visual Studio 2017 Community Edition" and "Microsoft rdlc report designer for visual studio 14.2" combination to try and reproduce this locally. Thank you!

With best regards,

Elmer

**Comment by hrplinktest** [comment]
Hi Elmer,

Please find the error logs below that I found in the event viewer.

--------------------------------------------------------------------------

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at System.Signature.GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.ReportDesigner.Design.DesignUtil.IsObjectDataSourceMethod(System.Reflection.MethodInfo)
   at Microsoft.ReportDesigner.Design.DesignUtil.ClassContainsObjectDataSourceMethod(System.Type)
   at Microsoft.ReportDesigner.Design.DesignUtil.GetVenusObjectDataSources(System.Xml.Schema.XmlSchema[], System.IServiceProvider)
   at Microsoft.ReportDesigner.Data.Local.DataSetSynchronizer+<GetProjectGenericObjectDataSources>d__24.MoveNext()
   at Microsoft.ReportDesigner.Data.Local.DataSetSynchronizer+<GetSynchableDataSources>d__0.MoveNext()
   at Microsoft.ReportDesigner.Data.Local.Dialogs.Pages.DataSetGeneralPage.LoadDataSources()
   at Microsoft.ReportDesigner.Data.Local.Dialogs.Pages.DataSetGeneralPage.LoadData()
   at Microsoft.ReportDesigner.Data.Local.Dialogs.DataSetDialog.OnLoad(System.EventArgs)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

--------------------------------------------------------------------------

Faulting application name: devenv.exe, version: 15.9.28307.586, time stamp: 0x5c9e3ce1
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xe6477cce
Exception code: 0xe0434352
Fault offset: 0x0012a892
Faulting process id: 0x5c0
Faulting application start time: 0x01d6dfab381cdaba
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 019f2317-21be-48fc-a0f1-ecb4ef032540
Faulting package full name:
Faulting package-relative application ID:

--------------------------------------------------------------------------

Fault bucket 1778501352105089686, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 15.9.28307.586
P3: 5c9e3ce1
P4: mscorlib
P5: 4.8.4250.0
P6: 5f2a0563
P7: 465a
P8: 0
P9: System.IO.FileLoadException
P10:

Attached files:
\\?\C:\Users\sherw\AppData\Roaming\microsoft\visualstudio\15.0_7e269941\activitylog.xml
\\?\C:\Users\sherw\AppData\Local\microsoft\visualstudio\15.0_7e269941\devenv.exe.config
\\?\C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.isolation.ini
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB3E0.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD311.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD331.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD32F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD35F.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_21aec86397c360b252356f53de5544bbeae2ac7_859bcbc6_b7f1e62a-e490-43e1-9d4e-ecd4822024ee

Analysis symbol:
Rechecking for solution: 0
Report Id: 019f2317-21be-48fc-a0f1-ecb4ef032540
Report Status: 268435456
Hashed bucket: b5c4263b6fde32b3b8ae818e8cc69a96
Cab Guid: 0

--------------------------------------------------------------------------


Thanks,

Sherwin
________________________________

**Comment by thinkingserious** [comment]
Hello @hrplinktest,

This error log seems to suggest that there is a file loading issue. Is there some file(s) that get loaded as part of this application?

With best regards,

Elmer

**Comment by hrplinktest** [comment]
Hi Elmer,

There's no file being loaded as part of the application.  It's happening to all our development team and not just on one machine.

Thanks,

Sherwin
________________________________

**Comment by JenniferMah** [comment]
Hi @hrplinktest 
Can you let us know which version of SendGrid you were previously using before updating to `SendGrid 9.22.0`?
