### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by bbajwa9366** [sendgrid/sendgrid-csharp#1097]
### Issue Summary
We use SendGrid's NuGet package in a ..net core MVC project, and face an exception while sending e-mail to users.
### Steps to Reproduce
Create SendGrid Client.
Create message
Add subject, sender, CCs, receiver, etc.
await client.SendEmailAsync(message, cancellationToken)
Every times we will receive an exception with the following stack trace:
### Code Snippet
```csharp
# var apiKey = _configuration["SendGridAPIkey"];
                var client = new SendGridClient(apiKey);
                var from = new SendGrid.Helpers.Mail.EmailAddress(model.Email.ToString(), model.Name);
                var subject = model.NatureOfContact + ":" + model.Subject + "(" + model.FranchiseNumber + " - " + model.StoreNumber + ")";
                var to = new SendGrid.Helpers.Mail.EmailAddress(_configuration["ToEmail"], "Example User");

                string text = model.Message.Replace(System.Environment.NewLine, "<br>");
                //text = text.Replace("", "&nbsp");

                var htmlContent = "<br><br> Sent Via the Customer Support page in the Blue Line Equipment Site:<br><br><br> Name: " + model.Name + "<br>Email: " + model.Email + "<br>Franchise #: " + model.FranchiseNumber + "<br>Store #: " + model.StoreNumber + "<br>Phone Number: " + model.PhoneNumber + "<br>Invoice #: " + model.InvoiceNumber + "<br><br>Message:<br> " + text;

                var msg = MailHelper.CreateSingleEmail(from, to, subject, null, htmlContent);
                List<IFormFile> attachements = model.Attachments;
                System.IO.Stream fs;
                System.IO.BinaryReader br;
                Byte[] bytes;
                string base64String;

                if (attachements != null)
                {
                    foreach (var file in attachements)
                    {
                        if (file.Length > 0)
                        {
                            fs = file.OpenReadStream();
                            br = new System.IO.BinaryReader(fs);
                            bytes = br.ReadBytes((Int32)fs.Length);
                            base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
                            msg.AddAttachment(file.FileName, base64String, null, "attachment", "banner");

                        }

                    }
                }

                var response = await client.SendEmailAsync(msg);


### Exception/Log
```
# Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
RequestId: 800000b1-0000-f700-b63f-84710c7967bb
RequestPath: /Home/SendEmail
SpanId: |f899407e-49bc315da43b8d1c.
TraceId: f899407e-49bc315da43b8d1c
ParentId: 

An unhandled exception has occurred while executing the request.

Exception: 
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.Helpers.Reliability.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SendGrid.BaseClient.MakeRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.BaseClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken)
   at SendGrid.BaseClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken)
   at BlueLineEquipment_Man19.Controllers.HomeController.SendEmail(ContactViewModel model) in C:\Users\bbajwa\Source\Repos\BlueLineOrdering\BluelineManualWEB\Controllers\HomeController.cs:line 695
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

### Technical details:
* sendgrid-csharp version: 
* csharp version:

**Comment by bbajwa9366** [comment]
sendgrid 9.22.0
Firewall port 443,465 and 587 is open and connection is ok
Working fine without Firewall

**Comment by thinkingserious** [comment]
Hello @bbajwa9366,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
