### ISSUE TITLE
Intermediate failures in send attempts

### ISSUE THREAD

**Issue by abirstolov** [sendgrid/sendgrid-csharp#1113]
### Issue Summary
I have already contacted Twilio SendGrid support (Adam F.), they have not found a solution and suggested I'll ask here.
My issue is that some of the send requests fail, a few a day out of hundreds.

It started after many OS patches have been installed (see attached)

### Steps to Reproduce
Send a lot of requests and wait basically.

### Exception/Log
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.Helpers.Reliability.RetryDelegatingHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.BaseClient.<MakeRequest>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.BaseClient.<RequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.BaseClient.<SendEmailAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Vaica.Notifiers.EmailSender.<SendAsync>d__4.MoveNext() 
```

### Technical details:
* OS: Windows Server 2012
* sendgrid-csharp version: 9.21.2
* Patches:
* ![windows-os-patches-31-03-2021-1](https://user-images.githubusercontent.com/3140921/119450270-4fd55300-bd3c-11eb-8507-e56c4b534586.png)
![windows-os-patches-31-03-2021-2](https://user-images.githubusercontent.com/3140921/119450279-52d04380-bd3c-11eb-9f7a-6df2cfb8d560.png)
[sendgrid-exception-stack-trace.txt](https://github.com/sendgrid/sendgrid-csharp/files/6537003/sendgrid-exception-stack-trace.txt)

**Comment by thinkingserious** [comment]
Hello @abirstolov,

This does not appear to be an issue with this helper library, but rather an underlying issue with the communication between your server and ours. There are some proposed solutions in [this StackOverflow thread](https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel), but I'm not sure which one would fix your particular issue.

Meanwhile, I suggest you [implement a retry strategy](https://github.com/sendgrid/sendgrid-csharp/blob/27effc4c3d7ad1abb55b6f071b5badd438a32f1a/USE_CASES.md#transient-fault-handling) for the failures.

With best regards,

Elmer
