### ISSUE TITLE
Invalid URI: The format of the URI could not be determined - when hosted

### ISSUE THREAD

**Issue by CGuthrie72** [sendgrid/sendgrid-csharp#1167]
### Issue Summary
Send email code works locally, but fails when run on hosted (IONOS).  I'm using a Blazor server app with .Net 6.

System.UriFormatException: Invalid URI: The format of the URI could not be determined.

The only difference from working local dev is the addition of a proxy server in the client call when hosted.

### Code Snippet
```csharp
    public async Task<int> SendAsync(
        string toEmail,
        string? toName,
        string subject,
        string htmlContent
        )
    {
        try
        {
            _logger.LogError("SendGrid: {@Config}", _emailConfiguration);

            var client = string.IsNullOrEmpty(_emailConfiguration.Proxy)
                ? new SendGridClient(_emailConfiguration.ApiKey)
                : new SendGridClient(_emailConfiguration.Proxy, _emailConfiguration.ApiKey);

            _logger.LogError("SendGrid: {@client}", client);

            var from = new EmailAddress("admin@linguatots.co.uk", "Linguatots");

            var to = new EmailAddress("sendgridtesting@gmail.com", toName);
            //to = new EmailAddress("craigguthrie72@hotmail.com", "CG");

            var plainTextContent = "and easy to do anywhere, even with C#";
            htmlContent = "test content";

            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            _logger.LogError("AFter CreateSingleEmail: {@msg}", msg);

            var response = await client.SendEmailAsync(msg).ConfigureAwait(false);

            _logger.LogError("Response: {@Response}", response);
            return 0;
        }
        catch (Exception e)
        {
            _logger.LogError(e, "SendGrid failed");
            return -1;
        }
    }
```

### Exception/Log
```
2022-03-14 11:36:27 [ERR] [AmberVert.Shared.Email.SendGrid.SendEmailService] [] SendGrid: {"ApiKey":"SG.**********","Proxy":"http://winproxy.server.lan:3128","$type":"EmailConfiguration"}

2022-03-14 11:36:27 [ERR] [AmberVert.Shared.Email.SendGrid.SendEmailService] [] SendGrid: {"UrlPath":null,"Version":"v3","MediaType":"application/json","$type":"SendGridClient"}

2022-03-14 11:36:27 [ERR] [AmberVert.Shared.Email.SendGrid.SendEmailService] [] AFter CreateSingleEmail: {"From":{"Name":"Linguatots","Email":"admin@linguatots.co.uk","$type":"EmailAddress"},"Subject":null,"Personalizations":[{"Tos":[{"Name":"CG","Email":"craigguthrie72@hotmail.com","$type":"EmailAddress"}],"Ccs":null,"Bccs":null,"From":null,"Subject":"test email","Headers":null,"Substitutions":null,"CustomArgs":null,"SendAt":null,"TemplateData":null,"$type":"Personalization"}],"Contents":[{"Type":"text/plain","Value":"and easy to do anywhere, even with C#","$type":"Content"},{"Type":"text/html","Value":"test content","$type":"Content"}],"PlainTextContent":null,"HtmlContent":null,"Attachments":null,"TemplateId":null,"Headers":null,"Sections":null,"Categories":null,"CustomArgs":null,"SendAt":null,"Asm":null,"BatchId":null,"IpPoolName":null,"MailSettings":null,"TrackingSettings":null,"ReplyTo":null,"$type":"SendGridMessage"}

2022-03-14 11:36:27 [ERR] [AmberVert.Shared.Email.SendGrid.SendEmailService] [] SendGrid failed
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at SendGrid.BaseClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken)
   at SendGrid.BaseClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken)
   at AmberVert.Shared.Email.SendGrid.SendEmailService.SendAsync(String toEmail, String toName, String subject, String htmlContent) in D:\dev\VS Projects\AmberVert.Blazor.6\AmberVert.Shared.Email.SendGrid\SendEmailService.cs:line 77
```

### Technical details:
* sendgrid-csharp version: 9.26.0
* csharp version: 10.0

**Comment by childish-sambino** [comment]
What are the options used to construct the `SendGridClient`? Specifically, the `host`?

**Comment by CGuthrie72** [comment]
As you can see in the log report above, it's my api key, starting SG (I've masked out the rest) and the proxy server for IONOS: "http://winproxy.server.lan:3128"

**Comment by CGuthrie72** [comment]
As you can see in the log report above, it's my api key, starting SG (I've masked out the rest) and the proxy server for IONOS: "http://winproxy.server.lan:3128"

**Comment by CGuthrie72** [comment]
Hi, thanks that was it, i had passed the proxy as a string  never spotted it.
