### ISSUE TITLE
For security reasons DTD is prohibited in this XML document

### ISSUE THREAD

**Issue by dr3x** [sendgrid/sendgrid-csharp#189]
Intermittently getting this error on calling 

await _transportWeb.DeliverAsync(mailMessage);

            From = "test@example.com",
            Recipients = new List<string>() { @"First Last <first.last@gmail.com>" },
            Subject = "Email Sender Automated Test",
            TextBody = "Hello World!"

Using valid emails; no xml in parameters...

"For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method."

Stack trace:
"   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at SendGrid.ErrorChecker.CheckForErrors(HttpResponseMessage response, Stream stream)
   at SendGrid.ErrorChecker.<CheckForErrorsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SendGrid.Web.<DeliverAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 ...

**Comment by paritoshmmmec** [comment]
Can I ask for some more code because I cannot see TextBody and Recipients properties?

**Comment by dr3x** [comment]
Turns out there were network issues and the component was attempting to read the html response that came back with the xml reader.  Would be nice to be able to detect the invalid response and give better error messaging but I'm going to close this for now as it is more of a network issue than a component issue.  Endpoint it was trying to hit was https://api.sendgrid.com/api/mail.send.xml - response that came back was from a different server.

Here is the code snippet where the error was getting thrown:
        private static void CheckForErrors(HttpResponseMessage response, Stream stream)
        {
            if (response.StatusCode != HttpStatusCode.OK)
            {
                using (var reader = XmlReader.Create(stream))
                {
                    while (reader.Read())
...
