### ISSUE TITLE
SendEmailAsync explodes when you don't have Microsoft.ApplicationInsights.AspNetCore package installed in your project, which contains System.Diagnostics.DiagnosticSource 

### ISSUE THREAD

**Issue by ryanelian** [sendgrid/sendgrid-csharp#442]
#### Issue Summary

`SendEmailAsync` explodes when you do not have `Microsoft.ApplicationInsights.AspNetCore` package installed in your project, which contains `System.Diagnostics.DiagnosticSource`.

Confirmed issue when removing the package causing error then reinstalling the said package made the error disappear.

#### Steps to Reproduce

1. Create new project: ASP.NET Core MVC using .NET Framework 4.7
2. Do not include `Microsoft.ApplicationInsights.AspNetCore` package in the project.
3. Send email:

```csharp
var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
var response = await client.SendEmailAsync(msg);
```

#### Technical details:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.<MakeRequest>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<RequestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<SendEmailAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Accelist.IdentityManagement.Services.EmailService.<SendWelcomeEmail>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Accelist.IdentityManagement.Services.EmployeeService.<AddNew>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Accelist.IdentityManagement.Controllers.EmployeeController.<Create>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

* sendgrid-csharp Version: 9.1.1 via NuGet
* .NET Version: 4.7

**Comment by ryanelian** [comment]
Upon analysis, this is caused by SendGrid relying on `System.Net.Http` 4.3.0, which is bugged.

According to this thread: https://github.com/dotnet/corefx/issues/15031

- `System.Net.Http` 4.3.0 incorrectly contains `System.Net.Http` 4.1.1 which references `System.Diagnostics.DiagnosticSource` 4.0.0 
- However, `System.Net.Http` 4.3.0 references `System.Diagnostics.DiagnosticSource` 4.3.0, which caused version mismatch.

**Solution:** SendGrid must include `System.Net.Http` 4.3.1 dependencies instead!

**Comment by ryanelian** [comment]
On a relevant but different issue, SendGrid dependencies over NuGet appeared to be wrongly defined for .NET Framework:

Compare: https://www.nuget.org/packages/Sendgrid and https://www.nuget.org/packages/Dapper

- `Dapper` relies on `System.Data.SqlClient` for querying. However, .NET Framework has `System.Data.SqlClient` accessible from `System.Data` framework assembly. [Source](https://msdn.microsoft.com/en-us/library/system.data.sqlclient(v=vs.110).aspx)
- Hence, Dapper does NOT refer to https://www.nuget.org/packages/System.Data.SqlClient/ when targeting .NET Framework, **only when targeting .NET Standard!!!**
- On contrary, [your nuspec file](https://github.com/sendgrid/sendgrid-csharp/blob/master/nuspec/Sendgrid.9.1.1.nuspec) refers to https://www.nuget.org/packages/System.Net.Http/ for .NET Framework; which is actually not needed because `System.Net.Http` [can be referenced via framework assembly](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.110).aspx)... (Since .NET Framework 4.5)

Therefore, your NuGet dependencies, rather than like this:

```
    .NETFramework 4.0
        Newtonsoft.Json (>= 9.0.1)
        System.Net.Http (>= 4.0.0)
    .NETStandard 1.3
        Microsoft.AspNetCore.Http.Abstractions (>= 1.1.0)
        NETStandard.Library (>= 1.6.1)
        Newtonsoft.Json (>= 9.0.1)
```

Probably should look more like this

```
    .NETFramework 4.0
        Newtonsoft.Json (>= 9.0.1)
        System.Net.Http (>= 4.3.1)
    .NETFramework 4.5
        Newtonsoft.Json (>= 9.0.1)
    .NETStandard 1.3
        Microsoft.AspNetCore.Http.Abstractions (>= 1.1.0)
        NETStandard.Library (>= 1.6.1)
        Newtonsoft.Json (>= 9.0.1)
```

Just my 2 cents.

**Comment by thinkingserious** [comment]
Thanks @ryanelian!

I've added this to our backlog for a fix.

**Comment by thinkingserious** [comment]
[Pero Matić](https://turinginc.io), who is awesome, has provided the following information to help solve this issue as well:

The reason it's crashing when using ASP.NET is because of the reference to System.Net.Http.

In the project.json file remove this reference: 
"System.Net.Http": "4.0.0" 

And in the dependencies section (underneath "Newtonsoft.Json": "9.0.1"), add a NuGet reference to:
"System.Net.Http": "4.3.1"

The modified sections should look like this:

```javascript
"dependencies": {
"Microsoft.AspNetCore.Http.Abstractions": "1.1.0",
"NETStandard.Library": "1.6.1",
"Newtonsoft.Json": "9.0.1",
"System.Net.Http": "4.3.1"
}

"frameworkAssemblies": {
"System.Runtime.Serialization": "4.0.0"
}
```
--------
He also provided some [sample code](https://drive.google.com/file/d/0B3C7kw5ijphRZlQwTXBYeWg1YW8/view?usp=sharing), with the following instructions: 

These are the changes:

**src\SendGrid\project.json** 
netstandard1.3 now references System.Net.Http version 4.3.1 from NuGet

**ExampleCoreProject\project.json**
upgraded System.Net.Http to 4.3.1

**ExampleNet45Project\App.config**
added a binding redirect for System.Net.Http. I noticed a bug when running ExampleNet45Project in VS2017 where the program crashes complaining about incorrect assembly versions for System.Net.Http. Nothing happens leaving this in VS2015.

The `.nuspec` file will need to be updated so that .NETStandard1.3 contains a dependency for System.Net.Http version 4.3.1.
--------
One more thing, before making the PR can you test against the attached example? It's a VS2017 solution for ASP.NET Core MVC which targets the full .NET Framework version 4.6.2. It should work, just update the SendGrid reference in the csproj file to the version containing the fix. 

The key for getting it to work in VS2017 targeting .NET 4.6.2 is in the csproj file to have a reference to:

`<PackageReference Include="System.Net.Http" Version="4.3.1" />`

Without this even the fixed version of SendGrid falls back to version 4.3.0 and that doesn't work.

**Comment by thinkingserious** [comment]
Since there has been no activity on this issue since March 1, 2020, we are closing this issue. Please feel free to reopen or create a new issue if you still require assistance. Thank you!
