### ISSUE TITLE
.NET Core 2.0 -  Async post ("/mail/send") of SendGrid Web API 3 fails with - A security error occurred

### ISSUE THREAD

**Issue by avindevexpert** [sendgrid/sendgrid-csharp#704]
#### Issue Summary
.NET Core 2.0 -  Async post ("/mail/send") of SendGrid Web API 3 fails with error : A security error occurred.

2018-06-21 10:43:17.982 FPKP01GSS1C ERROR An error occurred while sending the request. 
EXCEPTION OCCURRED:System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()Async 
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AssetMark.EmailProxy.Service.Providers.ServiceClient.SendGridServiceClient.<SendAsync>d__12.MoveNext() in E:\_v\15\s\Code\EmailProxyService\EmailProxy.Service\Providers\SendGridServiceClient.cs:line 155

#### Steps to Reproduce
I am calling post (mail/send) method of SendGrid Web API3 from .NET Core 2.0 service and sometimes on our Production server we received above error. Also have attached my implementation class file.

Implementation Class File - [SendGridServiceClient.txt](https://github.com/sendgrid/sendgrid-csharp/files/2129172/SendGridServiceClient.txt)

#### Technical details:
* Platform ASP .NET Core 2.0 Web API hosted on IIS.
* Windows Server 2008 R2 Standard
* sendgrid-csharp Version: 9.9.0
* netstandard2.0

**Comment by thinkingserious** [comment]
Hello @avindevexpert,

Thanks for reporting this. I'm not quite sure what is happening here, as I can't reproduce, but [this](this) may lead to a solution.

I'm going to leave this open on our backlog for further investigation.

With Best Regards,

Elmer

**Comment by avindevexpert** [comment]
Hello @thinkingserious 

I ran load test where we have trigger 17000 mails only once have received above mentioned error.

In our Production environment we are getting at least 2 occurrence of errors daily since we launch with SendGrid.

We have retry functionality in our application, so on second attempt emails gets posted successfully to the SendGrid.

Below are the dates and number of error occurred:
ErrorDate	       ErrorCount
2018-06-20	2
2018-06-21	1
2018-06-22	1
2018-06-23	1
2018-06-25	3
2018-06-26	2
2018-06-27	1
2018-06-29	4
2018-07-02	2
2018-07-03	5

@thinkingserious  - Do you think is related to server security settings or any other issue.

Thanks,
Avinash Ghawali

**Comment by thinkingserious** [comment]
Hello @avindevexpert,

This looks like a server side issue, possibly on our side. I suggest you reach out to our [support team](https://support.sendgrid.com) as they are better equipped to investigate these sorts of issues.

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
Closing as this is a non-library issue.
