### ISSUE TITLE
System.IO.IOException: Unable to read data from the transport connection: The connection was closed

### ISSUE THREAD

**Issue by JnanaPrakash** [sendgrid/sendgrid-csharp#732]
#### Issue Summary

This issue was not coming before . 
 var client = new SendGridClient(ConfigurationManager.AppSettings["ApiKey"]);
_client.SendEmailAsync(message);_// Error is raising here

### Stack Trace

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<MakeRequest>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<RequestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<SendEmailAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AG.Common.Message.MessageOperation.GetEmailResult(EmailSource source, Task`1 responseMessage)
   at AG.Common.Message.MessageOperation.SendEmail(EmailSource source, Boolean optinDone, String fileContent)
   at AG.Common.Message.MessageOperation.<>c__DisplayClass33_0.<SendQueuedEmail>b__0(QueueEmailEntity item)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<MakeRequest>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<RequestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendGrid.SendGridClient.<SendEmailAsync>d__21.MoveNext()<---

#### Technical details:

* sendgrid-csharp Version: 9.4.1.0
* Platform (WebForms, ASP.NET)
* .NET Version: 4.5.2

**Comment by JnanaPrakash** [comment]
sometime its getting success and most of the time its failing

**Comment by thinkingserious** [comment]
Hello @JnanaPrakash,

This looks like a networking issue. Does your application utilize other external services? If so, are they periodically failing also?

If not, I would suggest you reach out to our [support](https://support.sendgrid.com) for further assistance.

With Best Regards,

Elmer

**Comment by AmbroiseCouissin** [comment]
I have the exact same problem. Most of the call fails.

```
The issuance failed ||| System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToExactLengthAsync(Stream destination, UInt64 length, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SendGrid.SendGridClient.MakeRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken)
```

**Comment by AmbroiseCouissin** [comment]
Finally found out why. When we send an html content that is quite big and that an error comes back, this error happens instead of `Unauthorized` let's say. Our issue was the following: "{\"errors\":[{\"message\":\"Maximum credits exceeded\",\"field\":null,\"help\":null}]}"

**Comment by thinkingserious** [comment]
Thanks for sharing your results @AmbroiseCouissin!

@JnanaPrakash,

Were you able to figure out your issue?

**Comment by danielcongrove** [comment]
@AmbroiseCouissin How were you able to figure out the error that caused the issue? I'm periodically experiencing the same error, but we've only used about half of our credits for the month, so I don't think that's it.

**Comment by thinkingserious** [comment]
Hello @danielcongrove,

It seems like you may be experiencing [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/851). I suggest that you reach out to our [support team](https://support.sendgrid.com) so that look at your account specifically.

With Best Regards,

Elmer

**Comment by knadt** [comment]
Any feedback?

**Comment by childish-sambino** [comment]
@knadt I closed this this because the OP had not responded for a while and others were able to resolve their issues. If you're seeing something similar and the above does not help, recommend reaching out to our [support team](https://support.sendgrid.com) so that look at your account specifically.
