### ISSUE TITLE
Null reference with substitution data

### ISSUE THREAD

**Issue by rjrudman** [sendgrid/sendgrid-csharp#92]
If we add a substitution value which is null, we get a null reference error propagating up from the included SendGridMail.dll

We can easily work around this - but it took quite a while to figure out why we got that error. It should either have an exception telling you about it - or treat null as an empty string.

Stacktrace:

    at SendGrid.SmtpApi.Utils.Serialize[T](T objectToSerialize)
    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
    at System.String.Join(String separator, IEnumerable`1 values)
    at SendGrid.SmtpApi.HeaderSettingsNode.ToJson()
    at SendGrid.SmtpApi.HeaderSettingsNode.<ToJson>b__0(String k)
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    at System.String.Join(String separator, IEnumerable`1 values)
    at SendGrid.SmtpApi.HeaderSettingsNode.ToJson()
    at SendGrid.SmtpApi.HeaderSettingsNode.<ToJson>b__0(String k)
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    at System.String.Join(String separator, IEnumerable`1 values)
    at SendGrid.SmtpApi.HeaderSettingsNode.ToJson()
    at SendGrid.SmtpApi.Header.JsonString()
    at SendGrid.Web.FetchFormParams(ISendGrid message)
    at SendGrid.Web.AttachFormParams(ISendGrid message, MultipartFormDataContent content)
    at SendGrid.Web.Deliver(ISendGrid message)
    at Playground.Program.DoIt() in d:\Shnexy\Playground\Program.cs:line 55

Example code:

            //Reproduce sendgrid error
            var mailMessage = new SendGridMessage() { From = new MailAddress("rjrudman@gmail.com", "Rob") };
            mailMessage.Subject = "TestSubj";

            mailMessage.To = new [] { new MailAddress("rjrudman@gmail.com") };

            mailMessage.Html = "<html></html>";
            mailMessage.Text = "";
            mailMessage.EnableTemplateEngine("09a7919f-e5d3-4c98-b6b8-d8ac6171401d");
            mailMessage.AddSubstitution("RESP_URL", new List<string>() { null });

            var credentials = new NetworkCredential
            {
                UserName = "SNIP",
                Password = "SNIP"
            };
            var web = new Web(credentials);
            try
            {
                web.Deliver(mailMessage);
            }
            catch (Exception ex)
            {
                var y = 0;
                throw;
            }

**Comment by brandonmwest** [comment]
Thank you, fixing this in the next release.

**Comment by brandonmwest** [comment]
Fixed in 5.1.0
