### ISSUE TITLE
System.Net.Http.WinHttpException: A security error occurred

### ISSUE THREAD

**Issue by grana601** [sendgrid/sendgrid-csharp#941]
#### Technical details:

* sendgrid-csharp Version: **9.9.0**
* Platform : **ASP.NET Core 2.0**

#### Issue Summary:

This issue is coming while sending email  to user. This issue is coming some time, 2 or 3 time a day. Please let me know what is the reason for this issue.

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.Helpers.Reliability.RetryDelegatingHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.SendGridClient.<MakeRequest>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.SendGridClient.<RequestAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SendGrid.SendGridClient.<SendEmailAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at School.Api.Services.EmailService.<Send>d__5.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at School.Api.Services.EmailService.<SendEmailAsync>d__11.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at School.Api.Services.ControlPanelRepository.<SendAutomaticEmail>d__115.MoveNext()

**Comment by thinkingserious** [comment]
Hello @grana601,

Thanks for reporting this issue!

This looks like an intermittent networking error. I'm thinking these errors might happen when your server can't talk to ours correctly.

Understanding that the issue happens 2-3 times a day, can you please provide some context? (i.e. what percentage does 2-3 errors mean?)

My suggestion would be to catch this error in your code, log and implement some retry logic.

With best regards,

Elmer

**Comment by grana601** [comment]
2 % chance error comes in a day

**Comment by thinkingserious** [comment]
Hello @grana601,

I'm closing this issue as it's not related to this helper library. If you require further assistance on this issue, please open a ticket at https://support.sendgrid.com.

Thanks!

With best regards,

Elmer
