### ISSUE TITLE
HttpRequestException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full

### ISSUE THREAD

**Issue by componentspace** [sendgrid/sendgrid-csharp#942]
#### Issue Summary

The following exception is being thrown intermittently when sending email. It occurs infrequently and the system doesn't appear to be under load at the time.

System.Net.Http.HttpRequestException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full ---> System.Net.Sockets.SocketException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SendGrid.SendGridClient.MakeRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken)

What's causing this issue and is there a workaround? 

Thanks.

#### Steps to Reproduce

The application startup includes the following.

            services.AddHttpClient<EmailService>();

The EmailService class includes:

public class EmailService
{
    private readonly HttpClient httpClient;

    public EmailService(HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }

    public async Task SendEmailAsync(...)
    {
        var sendGridClient = new SendGridClient(httpClient, sendGridApiKey);

        var sendGridMessage = new SendGridMessage()
        {
            From = new EmailAddress(from, fromName),                
            Subject = subject,
            HtmlContent = content
        };

        sendGridMessage.AddTo(emailMessage.To);

        var response = await sendGridClient.SendEmailAsync(sendGridMessage);
    }
}

Previous to this code we were calling new SendGridClient(sendGridApiKey) but this resulted in the same exception being thrown intermittently. 

#### Technical details:

* sendgrid-csharp Version: 9.12.0
* Platform ASP.NET Core
* .NET Version: 2.2

**Comment by thinkingserious** [comment]
Hello @componentspace,

Thanks for reporting this to us!

There looks to be some solutions to try [here](https://stackoverflow.com/questions/17167977/httpwebrequest-issue-system-lacked-sufficient-buffer-space-or-because-a-queue-w). Could you please take a look and let us know? 

I'd also add some retry logic around your `SendEmailAsync` call.

With best regards,

Elmer

**Comment by aevitas** [comment]
@componentspace Could you please verify that the `HttpClient` you are configuring with DI is actually being used properly within the SendGrid library? We've recently introduced support for re-using `HttpClient`, so this could definitely be a bug with the library, but we would need more details to pinpoint if and where it's potentially going wrong within the SendGrid client.

Thank you!

**Comment by componentspace** [comment]
@thinkingserious I've seen that SO post but I'm not entirely sure it's relevant. Editing the registry isn't possible as it's a hosted environment.

@aevitas I'm happy to provide more details if you can tell me exactly what you need. I'm not sure what you mean by verifying the HttpClient is being used properly within SendGrid. How would I do that?

Originally we were calling new SendGridClient(sendGridApiKey) and not passing in the DI supplied HttpClient. This resulted in the same exception so we switched to the IHttpClientFactory pattern (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0#consumption-patterns) but this hasn't made any difference.

We use this same pattern for a couple of other services within the same application but the exception has only occurred when calling SendGrid.

**Comment by componentspace** [comment]
Sorry, I didn't mean to close the issue.

**Comment by shwetasawant119** [comment]
I have been facing same issue. We have multiple Ajax calls to services of type POST. Even if we do changes in registry if load on website increases it will show same error.

**Comment by componentspace** [comment]
I noticed the status is "waiting for feedback". If someone is waiting for feedback from me, please advise exactly what you're after. Thanks.

**Comment by thinkingserious** [comment]
Hello @componentspace, @shwetasawant119,

Have you tried implementing [retry logic](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transient-fault-handling)?

Thanks for helping out @aevitas!

With best regards,

Elmer

**Comment by componentspace** [comment]
Thanks for the link. We've added our own retry logic but may switch to the inbuilt support at some stage.

**Comment by thinkingserious** [comment]
I am closing this one since I don't see anything else to be done from a helper library standpoint. 

If you disagree, please add a comment. Thanks!
