### ISSUE TITLE
Random Error Generated in Email sending.

### ISSUE THREAD

**Issue by govi2010** [sendgrid/sendgrid-csharp#958]
#### Issue Summary

We are facing issue in Email sending. Our email Template is big html content.

and Sometimes we are getting the following Error.
```
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToExactLengthAsync(Stream destination, UInt64 length, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SendGrid.SendGridClient.MakeRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken)
```

#### Steps to Reproduce

This issue comes randomly. 1) We have an HTML email template which is quite big.

#### Technical details:

* sendgrid-csharp Version: latest from nuget
* Platform ASP.NET Core
* .NET Core Version: 2.2

**Comment by govi2010** [comment]
```
at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SendGrid.SendGridClient.MakeRequest(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 194
   at SendGrid.SendGridClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken) in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 245
   at SendGrid.SendGridClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken) in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 256
```

**Comment by thinkingserious** [comment]
Hello @govi2010,

There is a [30 MB limit](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations) on the total size of your email. Could you check if you are over that limit?

If that is not the issue, could you please share the code you are using to send the email so that we can try and reproduce?

With best regards,

Elmer

**Comment by govi2010** [comment]
now it is working fine. The issue got fixed automatically.
